(let ((default-directory "~/.emacs.d/"))
  (normal-top-level-add-subdirs-to-load-path))

(mapc
 'require
 '(magit
   slime
   smex
   smartparens
   auto-complete
   ido
   ido-ubiquitous
   visible-mark
   dired
   dired-efap
   stumpwm-mode
   misc
   simp
   move-dup
   emux-session
   expand-region
   winner
   midnight
   isearch-symbol-at-point
   multiple-cursors
   itail
   powerline
   smart-indent-rigidly
   my-yas
   my-erc
   my-isearch
   my-advice
   my-backup
   my-package
   my-emms
   my-autoloads
   my-add-to-lists
   my-project-defenitions
   my-functions
   my-keybindings
   my-hooks
   my-settings
   my-emux-templates
   my-initializers))
