(add-to-list 'auto-mode-alist '("\\.scss" . css-mode))
(add-to-list 'auto-mode-alist
             '("\\(?:\\.rb\\|ru\\|rake\\|thor\\|jbuilder\\|gemspec\\|podspec\\|/\\(?:Gem\\|Rake\\|Cap\\|Thor\\|Vagrant\\|Guard\\|Pod\\)file\\)\\'" . enh-ruby-mode))
(add-to-list 'auto-mode-alist '("\\.stumpwmrc'" . stumpwm-mode))
(add-to-list 'auto-mode-alist '("\\.hamlbars'" . haml-mode))
(add-to-list 'auto-mode-alist '("\\.hamlc'" . haml-mode))
(add-to-list 'auto-mode-alist '("\\.js\\'" . rjsx-mode))
(add-to-list 'auto-mode-alist '("\\.jsx\\'" . rjsx-mode))
(define-derived-mode typescript-tsx-mode web-mode "TypeScript-tsx")
(add-to-list 'auto-mode-alist '("\\.tsx\\'" . typescript-tsx-mode))
(require 'flycheck)
(require 'tide)
(flycheck-add-next-checker 'typescript-tide '(warning . javascript-eslint) 'append)
(provide 'my-add-to-lists)
