(add-to-list 'auto-mode-alist '(".scss" . css-mode))
(add-to-list 'auto-mode-alist '(".rake" . ruby-mode))
(add-to-list 'auto-mode-alist '(".ru" . ruby-mode))
(add-to-list 'auto-mode-alist '("Gemfile" . ruby-mode))
(add-to-list 'auto-mode-alist '("Guardfile" . ruby-mode))
(add-to-list 'auto-mode-alist '("Rakefile" . ruby-mode))
(add-to-list 'auto-mode-alist '(".stumpwmrc'" . stumpwm-mode))
(add-to-list 'auto-mode-alist '(".hamlbars'" . haml-mode))
(add-to-list 'auto-mode-alist '(".hamlc'" . haml-mode))
(provide 'my-add-to-lists)
