(smex-initialize)
(icomplete-mode)
(ido-mode t)
(ido-ubiquitous-mode t)
(winner-mode)
(go-to-hell-bars)
(recentf-mode t)
(show-paren-mode t)
(auto-compression-mode 1)
(powerline-default-theme)
(provide 'my-initializers)
