(smex-initialize)
(icomplete-mode)
(ido-mode t)
(go-to-hell-bars)
(recentf-mode t)
(show-paren-mode t)
(highline-mode)
(auto-compression-mode 1) ; Lets emacs uncompress .gz files before opening them
(yas-global-mode 1)
(provide 'my-initializers)
