(emux-create-screen nil "~/code/artifex" "garbage" "rake jasmine")
(emux-create-terminal "mongodb" "rm -rf /data/db/mongod.lock && ~/.mongo/mongodb-linux-x86_64-1.6.5/bin/mongod")
(emux-create-screen nil nil "rs" "rs")
(emux-hsplit "rc" "rc")
(emux-vsplit "mongo" "sleep 5 && mongo artifex_development")
(emux-create-screen "tests" nil "rake")
(emux-send-to-terminal "rake spec")
(emux-vsplit "cucumber")
(emux-send-to-terminal "cok")
(emux-create-screen "git" nil "git" "git status")
