(emux-session-set-default-directory "~/code/crushee")
;; (emux-screen-create '(:name "bg") "jasmine" "rake jasmine")
;; (emux-terminal-create "mongodb" "rm -rf /data/db/mongod.lock && mongod")
(emux-terminal-create "rs" "rs")
(emux-terminal-hsplit "rc" "rc")
;; (emux-terminal-vsplit "mongo" "sleep 5 && mongo artifex_development")
(emux-screen-create '(:name "tests") "rspec")
(emux-terminal-send-raw "rake spec")
(emux-terminal-vsplit "cucumber")
(emux-terminal-send-raw "cok")
(emux-screen-create '(:name "misc") "misc")
(emux-screen-create '(:name "git") "git" "git status")
