(emux-session-set-default-directory "~/code/crushee")
(emux-term-create "server" "rs &")
(emux-session-name-buffer
 (itail "log/development.log"))
(emux-term-hsplit "rc" "rc")
(emux-screen-create '(:name "tests") "rspec")
(emux-term-send-raw "rake spec")
(emux-term "cucumber")
(emux-term-send-raw "cok")
(emux-screen-create '(:name "misc") "misc")
(emux-screen-create '(:name "git") "git" "git status")
