(emux-set-session-pwd "/other/downloads")
(emux-create-screen nil "download-dir" "lm")
(emux-hsplit "sb" "ssh sb")
(emux-terminal-command "ll d/ --sort time -r")
(emux-vsplit "rsync" "download_sync")
