(emux-set-session-pwd "~/code/murdersnake")
(emux-create-screen nil "garbage" "rake jasmine")
(emux-create-terminal "rs" "rs")
(emux-hsplit "rc" "rc")
(emux-vsplit "rdbc" "rdbc")
(emux-create-screen "tests" "rspec")
(emux-send-to-terminal "rake spec")
(emux-send-to-terminal "cok")
(emux-create-screen nil "misc")
(emux-create-screen nil "git" "git status")
